mailing:
  MAILGUN_DOMAIN: <>
  MAILGUN_API_KEY: <>
  recipients:
    - test@test.com

projects:
  - name: sublime-text
    snap: https://github.com/snapcrafters/sublime-text.git
    type: scriptlet
  - name: pyside2
    snap: https://github.com/om26er/pyside2-snap.git
    type: pypi
