name: surc
base: core18
version: '0.1'
summary: Snap Upstream Release Checker
description: |
  Snap Upstream Release Checker 

grade: stable
confinement: strict

parts:
  surc:
    plugin: dump
    source: .
    prime:
      - scriptlets
      - surc.py
      - surc.wrapper
  launcher:
    plugin: python
    source: .
    requirements:
      - requirements.txt
    stage-packages:
      - curl
      - jq
      - wget

apps:
  surc:
    command: surc.wrapper
    environment:
      LC_ALL: en_US.UTF-8
    plugs:
      - network
      - home
